include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Suppress deprecated warnings for withOpacity (planned migration to withValues)
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    # Allow print in debug mode
    avoid_print: ignore
    # Allow BuildContext usage across async gaps (with proper checks)
    use_build_context_synchronously: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - use_key_in_widget_constructors
